# Generated by Django 5.1.7 on 2025-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroEmprendedores', '0006_alter_entrepreneur_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='viernes',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='jueves_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='jueves_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='lunes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='lunes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='martes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='martes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='miercoles_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='miercoles_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='viernes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='viernes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
